/**
 * سجل المواقع الأثرية الرسمية في جمهورية العراق
 * Official Registry of Archaeological & Cultural Heritage Sites in Iraq
 * 
 * المصادر المعتمدة والرسمية:
 * 1. مركز التراث العالمي لليونسكو (UNESCO World Heritage Centre)
 * 2. القائمة التمهيدية لليونسكو لجمهورية العراق (UNESCO Tentative List for Iraq) - محدثة 2025/2026
 * 3. الهيئة العامة للآثار والتراث العراقية (State Board of Antiquities and Heritage - SBAH)
 * 4. مسوحات وقواعد بيانات الآثار الميدانية المعتمدة دولياً (British Museum Iraq Scheme, EAMENA)
 */

(function (window) {
  'use strict';

  const IRAQ_ARCHAEOLOGY_DATA = {
    metadata: {
      titleAr: 'سجل المواقع الأثرية والتراث العالمي في العراق',
      titleEn: 'Official Archaeological & World Heritage Sites of Iraq',
      providerAr: 'الهيئة العامة للآثار والتراث (SBAH) • مركز التراث العالمي لليونسكو (UNESCO)',
      providerEn: 'State Board of Antiquities and Heritage (SBAH) & UNESCO World Heritage Centre',
      lastUpdated: '2025 / 2026',
      totalSites: 40,
      categories: {
        unesco_inscribed: {
          labelAr: 'موقع تراث عالمي معتمد (UNESCO)',
          labelEn: 'UNESCO World Heritage Site',
          color: '#f59e0b', // Gold / Amber
          badgeClass: 'bg-amber-500/20 text-amber-300 border border-amber-500/40',
          pinIcon: 'fa-landmark'
        },
        unesco_tentative: {
          labelAr: 'القائمة التمهيدية لليونسكو (Tentative List)',
          labelEn: 'UNESCO Tentative List',
          color: '#0284c7', // Sky / Cyan
          badgeClass: 'bg-sky-500/20 text-sky-300 border border-sky-500/40',
          pinIcon: 'fa-monument'
        },
        national_registered: {
          labelAr: 'معلم أثري وطني مسجل (SBAH)',
          labelEn: 'National Registered Antiquity',
          color: '#10b981', // Emerald
          badgeClass: 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40',
          pinIcon: 'fa-archway'
        }
      }
    },

    sites: [
      // =========================================================================
      // 1. مواقع التراث العالمي المعتمدة رسمياً في اليونسكو (UNESCO Inscribed)
      // =========================================================================
      {
        id: 'unesco-babylon',
        nameAr: 'مدينة بابل الأثرية',
        nameEn: 'Babylon Archaeological Site',
        ancientName: 'Bāb-Ilim (بوابة الإله)',
        governorate: 'بابل',
        category: 'unesco_inscribed',
        unescoRef: '278',
        inscribedYear: 2019,
        lat: 32.5422,
        lng: 44.4211,
        civilization: 'الحضارة البابلية (العهد القديم والحديث 1894 - 539 ق.م)',
        period: 'العصر البابلي القديم والحديث',
        descriptionAr: 'عاصمة الإمبراطورية البابلية ومقر حمورابي ونبوخذ نصر الثاني، وأعظم عواصم العالم القديم. تضم أسوار بابل المزدوجة، وبوابة عشتار الشهيرة المزينة بحيوانات التنين السيروش وموكب الآلهة، وقصر نبوخذ نصر الجنوبي، ومعبد إيساكيلا المخصص للإله مردوخ، وأسد بابل البازلتي، وزقورة إيتيمينانكي (أساس برج بابل التاريخي).',
        descriptionEn: 'The seat of the Neo-Babylonian Empire and Hammurabi. Features the Ishtar Gate, the Processional Way, Esagila Temple of Marduk, the Southern Palace, and the Lion of Babylon.',
        keyMonuments: ['بوابة عشتار', 'شارع الموكب', 'أسد بابل', 'القصر الجنوبي', 'معبد إيساكيلا', 'زقورة إيتيمينانكي'],
        unescoUrl: 'https://whc.unesco.org/en/list/278'
      },
      {
        id: 'unesco-ur',
        nameAr: 'مدينة أور الكلدانيين وزقورة أور العظيمة',
        nameEn: 'Ur Archaeological City & Ziggurat',
        ancientName: 'Urim (أوريم)',
        governorate: 'ذي قار',
        category: 'unesco_inscribed',
        unescoRef: '1481',
        inscribedYear: 2016,
        lat: 30.9622,
        lng: 46.1030,
        civilization: 'الحضارة السومرية والأكدية (سلالة أور الثالثة 2112 - 2004 ق.م)',
        period: 'العصر السومري (أور الثالثة)',
        descriptionAr: 'واحدة من أهم وأقدم المدن السومرية في جنوب الرافدين ومسقط رأس خليل الله إبراهيم. شيد ملكها أور-نامو زقورة أور العظيمة المخصصة لإله القمر (نانا/سين)، وتضم المقبرة الملكية الشهيرة (كنوز شبعاد وقيثارة أور الذهبية)، وقصر شولجي، ودور أور السكنية المنتظمة.',
        descriptionEn: 'Major Sumerian city-state and birthplace of Prophet Abraham. Home to the great Ziggurat of Ur built by King Ur-Nammu, the Royal Tombs of Ur, and E-gish-nu-gal temple.',
        keyMonuments: ['زقورة أور الكبرى', 'المقبرة الملكية', 'قصر أور-نامو', 'بيت إبراهيم الخليل', 'معبد نانا'],
        unescoUrl: 'https://whc.unesco.org/en/list/1481'
      },
      {
        id: 'unesco-uruk',
        nameAr: 'مدينة الوركاء الأثرية (أوروك)',
        nameEn: 'Ancient City of Uruk (Warka)',
        ancientName: 'Unug (أونوك / أوروك)',
        governorate: 'المثنى',
        category: 'unesco_inscribed',
        unescoRef: '1481',
        inscribedYear: 2016,
        lat: 31.3222,
        lng: 45.6408,
        civilization: 'الحضارة السومرية (فجر السلالات وملحمة كلكامش ~4000 - 2000 ق.م)',
        period: 'عصر الوركاء وفجر السلالات',
        descriptionAr: 'مهد الثورة الحضرية الأولى في تاريخ البشرية وحاضرة الملك الأسطوري كلكامش. منها انطلقت أقدم كتابة مسمارية تصويرية في العالم (~3200 ق.م). تضم مجمع معبد إيانا المكرس للإلهة عشتار، والمعبد الأبيض المرتفع فوق زقورة آنو، وأسوار المدينة الدفاعية الضخمة.',
        descriptionEn: 'Cradle of urban civilization and writing (cuneiform script c. 3200 BCE). City of King Gilgamesh featuring the Eanna precinct of Inanna and the White Temple on the Anu Ziggurat.',
        keyMonuments: ['معبد إيانا', 'المعبد الأبيض وزقورة آنو', 'أسوار كلكامش', 'أقدم رُقم طينية للكتابة'],
        unescoUrl: 'https://whc.unesco.org/en/list/1481'
      },
      {
        id: 'unesco-eridu',
        nameAr: 'موقع إريدو الأثري (تل أبو شهرين)',
        nameEn: 'Eridu Archaeological Site (Tell Abu Shahrain)',
        ancientName: 'Eridug (نونكي / إريدو)',
        governorate: 'ذي قار',
        category: 'unesco_inscribed',
        unescoRef: '1481',
        inscribedYear: 2016,
        lat: 30.8158,
        lng: 45.9969,
        civilization: 'العصر العبيدي والسومري المبكر (~5400 - 2000 ق.م)',
        period: 'فترة العبيد والعصر السومري القديم',
        descriptionAr: 'وفق قائمة الملوك السومرية هي "أول مدينة هبطت فيها الملوكية من السماء"، وأقدم مستوطنة دينية حضرية في جنوب بلاد الرافدين. تضم تلالاً لـ 18 طبقة معبدية متعاقبة كرست للإله إنكي (إيا)، إله الحكمة والمياه العذبة، وتوثق نشوء العمارة الدينية الميزوبوتامية.',
        descriptionEn: 'Regarded in Sumerian king list as the first city in the world where kingship descended from heaven. Center of the cult of god Enki with 18 successive temple strata.',
        keyMonuments: ['معبد الإله إنكي', 'زقورة إريدو العبيدية', 'الطبقات المعبدية الـ 18'],
        unescoUrl: 'https://whc.unesco.org/en/list/1481'
      },
      {
        id: 'unesco-hatra',
        nameAr: 'مدينة الحضر الأثرية (مملكة عربايا)',
        nameEn: 'Hatra Archaeological City',
        ancientName: 'Hatrā (بيت إيلها شمش)',
        governorate: 'نينوى',
        category: 'unesco_inscribed',
        unescoRef: '277',
        inscribedYear: 1985,
        lat: 35.5861,
        lng: 42.7236,
        civilization: 'المملكة العربية الحضرية والبارثية (القرن 2 ق.م - القرن 3 م)',
        period: 'العصر الهلنستي والحضري البارثي',
        descriptionAr: 'عاصمة أول مملكة عربية موثقة في الجزيرة الفراتية، صمدت بأسوارها المزدوجة المنيعة وأبراجها الـ 160 أمام الحصار الروماني بقيادة تراجان وسيبتيموس سيفيروس. تتميز بعمارتها الفريدة التي تمزج الفن الشرقي العراقي مع التأثيرات الهلنستية، وأقواس معبد الشمس الكبير وتماثيل الملوك سنطروق الأول والثاني.',
        descriptionEn: 'Capital of the Arab Kingdom of Hatra. A fortified city that resisted Roman invasions twice, showcasing a unique blend of Hellenistic and eastern Mesopotamian architecture.',
        keyMonuments: ['المعبد الكبير للإله شمش', 'أقواس الإيوان الحجري', 'سور الحضر الخارجي والداخلي', 'تماثيل الملوك سنطروق'],
        unescoUrl: 'https://whc.unesco.org/en/list/277'
      },
      {
        id: 'unesco-ashur',
        nameAr: 'آشور (قلعة الشرقاط)',
        nameEn: 'Ashur (Qal\'at Sherqat)',
        ancientName: 'Aššur (آشور)',
        governorate: 'صلاح الدين',
        category: 'unesco_inscribed',
        unescoRef: '1130',
        inscribedYear: 2003,
        lat: 35.4572,
        lng: 43.2642,
        civilization: 'الإمبراطورية الآشورية (2500 - 614 ق.م)',
        period: 'العصر الآشوري القديم والوسيط والحديث',
        descriptionAr: 'المهد الأول والعاصمة الدينية والروحية للإمبراطورية الآشورية ومقر الإله القومي آشور. تطل بموقعها الاستراتيجي على نهر دجلة، وتضم زقورة آشور الشامخة، ومعبد آنو وأدد المزدوج، والقصر القديم، والأبواب الحجرية وسور التابوت الضخم.',
        descriptionEn: 'The religious and first capital of the Assyrian Empire. Overlooks the Tigris and contains the Ziggurat of Ashur, the temple of Anu-Adad, and the Old Palace.',
        keyMonuments: ['زقورة آشور', 'معبد آنو وأدد المزدوج', 'القصر القديم', 'السور الحجري المطل على دجلة'],
        unescoUrl: 'https://whc.unesco.org/en/list/1130'
      },
      {
        id: 'unesco-samarra',
        nameAr: 'مدينة سامراء الأثرية والجامع الملوية',
        nameEn: 'Samarra Archaeological City',
        ancientName: 'Surra Man Ra\'a (سر من رأى)',
        governorate: 'صلاح الدين',
        category: 'unesco_inscribed',
        unescoRef: '276',
        inscribedYear: 2007,
        lat: 34.2069,
        lng: 43.8744,
        civilization: 'الخلافة العباسية الإسلامية (836 - 892 م)',
        period: 'العصر العباسي الذهبي',
        descriptionAr: 'العاصمة الثانية للخلافة العباسية بعد بغداد وأكبر موقع حضري إسلامي محفوظ في العالم يمتد بطول 40 كم على ضفاف دجلة. تضم جامع المتوكل ومئذنته الملوية الحلزونية الشهيرة بارتفاع 52م، وجامع ومئذنة أبي دلف، وقصر العاشق والمعشوق، ودار الخلافة (قصر الجوسق الخاقاني) وميدان سباق الخيل.',
        descriptionEn: 'The Abbasid capital built during the 9th century. Features the Great Mosque and its spiral Malwiya minaret (52m), Abu Dulaf mosque, Al-Ashiq palace, and the Caliphal palace.',
        keyMonuments: ['المئذنة الملوية وجامع المتوكل', 'جامع ومئذنة أبي دلف', 'قصر العاشق والمعشوق', 'دار الخلافة (الجوسق الخاقاني)'],
        unescoUrl: 'https://whc.unesco.org/en/list/276'
      },
      {
        id: 'unesco-erbil-citadel',
        nameAr: 'قلعة أربيل التاريخية',
        nameEn: 'Erbil Citadel',
        ancientName: 'Arba-ilu (مدينة الآلهة الأربعة)',
        governorate: 'أربيل',
        category: 'unesco_inscribed',
        unescoRef: '1437',
        inscribedYear: 2014,
        lat: 36.1911,
        lng: 44.0092,
        civilization: 'مستوطنة بشرية متصلة لأكثر من 6000 عام (من العصر الحجري حتى العصر الحديث)',
        period: 'العصر النيوليتي، الآشوري، الإسلامي',
        descriptionAr: 'أقدم قلعة مأهولة بالسكان بشكل متواصل في تاريخ البشرية، ترتفع على تل أثري بيضاوي يبلغ ارتفاعه 30 متراً فوق سهول أربيل. كانت مركزاً رئيسياً لعبادة الإلهة عشتار في العصر الآشوري. تضم النسيج العمراني التراثي، وحمام القلعة العثماني، وبوابة أحمدي، وقصور الأعيان ذات الزخارف الجصية.',
        descriptionEn: 'One of the oldest continuously inhabited settlements in the world, sitting atop a 30m-high archaeological tell. Features Ottoman-era mansions, traditional alleyways, and ancient ramparts.',
        keyMonuments: ['بوابة أحمدي الدفاعية', 'حمام القلعة التاريخي', 'الجامع الكبير', 'متحف القلعة والنسيج التراثي'],
        unescoUrl: 'https://whc.unesco.org/en/list/1437'
      },

      // =========================================================================
      // 2. مواقع القائمة التمهيدية الرسمية لليونسكو (UNESCO Tentative List)
      // =========================================================================
      {
        id: 'tentative-aqar-quf',
        nameAr: 'موقع عقرقوف وزقورة دور كوريغالزو (مدرج رسمياً 2025)',
        nameEn: 'Dur-Kurigalzu (Aqar Quf)',
        ancientName: 'Dūr-Kurigalzu (حصن كوريغالزو)',
        governorate: 'بغداد',
        category: 'unesco_tentative',
        unescoRef: '6797',
        inscribedYear: 2025,
        lat: 33.3561,
        lng: 44.2017,
        civilization: 'السلالة الكاشية في بابل (القرن 14 ق.م)',
        period: 'العصر البابلي الكاشي (~1400 ق.م)',
        descriptionAr: 'أحدث موقع أثري عراقي أدرج رسمياً على القائمة التمهيدية لليونسكو (2025). أسسها الملك الكاشي كوريغالزو الأول كعاصمة لحماية الطرق التجارية. زقورتها الشهيرة ترتفع 57 متراً وتتميز بوجود طبقات البردي وحبال القصب الأصلية الصامدة منذ أكثر من 3400 عام بين مداميك الآجر واللبن.',
        descriptionEn: 'The Kassite capital founded by Kurigalzu I, newly inscribed on UNESCO tentative list in 2025. Its remarkable ziggurat rises 57m with preserved woven reed mats embedded in mudbrick.',
        keyMonuments: ['زقورة عقرقوف الصامدة', 'القصر الكاشي الملكي', 'مجمع المعابد التذكارية'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/6797/'
      },
      {
        id: 'tentative-nimrud',
        nameAr: 'كالح / نمرود الأثرية',
        nameEn: 'Nimrud (Ancient Kalhu)',
        ancientName: 'Kalḫu (كالح)',
        governorate: 'نينوى',
        category: 'unesco_tentative',
        unescoRef: '1463',
        inscribedYear: 2000,
        lat: 35.9986,
        lng: 43.3278,
        civilization: 'الإمبراطورية الآشورية الحديثة (879 - 612 ق.م)',
        period: 'العصر الآشوري الحديث',
        descriptionAr: 'العاصمة الآشورية الإمبراطورية الكبرى التي بناها الملك آشور ناصربال الثاني واحتفل بتدشينها في مأدبة أسطورية سجلت على مسلة النمرود. تضم القصر الشمالي الغربي، والثيران المجنحة (اللاماسو)، وزقورة نمرود، وقصر شلمنصر، ومجموعات العاجيات الملكية الشهيرة.',
        descriptionEn: 'The grand imperial capital of Ashurnasirpal II on the Tigris. Home to the Northwest Palace, colossal winged bull colossi (lamassu), the Ziggurat, and the Nimrud Ivories.',
        keyMonuments: ['قصر آشور ناصربال الشمالي الغربي', 'ثيران اللاماسو المجنحة', 'زقورة نمرود', 'المسلة السوداء لشلمنصر'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/1463/'
      },
      {
        id: 'tentative-nineveh',
        nameAr: 'مدينة نينوى الأثرية وقصور سنحاريب',
        nameEn: 'The Ancient City of Nineveh',
        ancientName: 'Ninua (نينوى)',
        governorate: 'نينوى',
        category: 'unesco_tentative',
        unescoRef: '1465',
        inscribedYear: 2000,
        lat: 36.3589,
        lng: 43.1517,
        civilization: 'الإمبراطورية الآشورية الحديثة (عهد سنحاريب وآشوربانيبال 705 - 612 ق.م)',
        period: 'أوج العصر الآشوري',
        descriptionAr: 'أعظم حاضرة وعاصمة في الشرق الأدنى القديم، وسعت في عهد سنحاريب لتكون عاصمة العالم. تضم تل قوينجق، قصر سنحاريب المسمى "القصر الذي لا يضاهيه قصر"، ومكتبة آشوربانيبال الملكية التي حوت أكثر من 30 ألف رقيم مسماري منها ملحمة كلكامش وقصة الطوفان، وبوابات السور التاريخية كبوابة ماشكي ونرغال.',
        descriptionEn: 'The sprawling capital of Sennacherib and Ashurbanipal. Site of the Royal Library of Ashurbanipal, Kuyunjik tell, Nebi Yunus, and monumental stone gates like Nergal and Mashki.',
        keyMonuments: ['تل قوينجق ومكتبة آشوربانيبال', 'قصر سنحاريب الحجري', 'بوابة ماشكي وبوابة نرغال', 'تل النبي يونس'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/1465/'
      },
      {
        id: 'tentative-nippur',
        nameAr: 'مدينة نفر الأثرية (نيبور)',
        nameEn: 'Nippur Holy City',
        ancientName: 'Nibru (نيبورو)',
        governorate: 'القادسية',
        category: 'unesco_tentative',
        unescoRef: '6173',
        inscribedYear: 2017,
        lat: 32.1258,
        lng: 45.2308,
        civilization: 'الحضارة السومرية والبابلية (الألف الرابع ق.م - القرن 8 م)',
        period: 'العصر السومري والبكتيري والإسلامي المبكر',
        descriptionAr: 'العاصمة الروحية والدينية الأولى لبلاد سومر وأكد، ومركز تقديس كبير الآلهة السومرية "إنليل". لم تكن مقراً لسلالة حاكمة بل كانت المدينة المقدسة التي يطلب ملوك بلاد الرافدين جميعاً الشرعية منها. تضم معبد إيكور (بيت الجبل)، وزقورة نفر، وحي المدارس والكتبة السومرية.',
        descriptionEn: 'The religious heart of ancient Sumer, center of the worship of chief deity Enlil. Kings sought sacred legitimacy here. Features the Ekur temple, the ziggurat, and the scribal school.',
        keyMonuments: ['معبد إيكور المقدس', 'زقورة نيبور', 'حي الكتبة والمدارس السومرية'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/6173/'
      },
      {
        id: 'tentative-ukhaidar',
        nameAr: 'حصن الأخيضر الأثري',
        nameEn: 'The Fortress of Al-Ukhaidar',
        ancientName: 'قصر الأخيضر',
        governorate: 'كربلاء',
        category: 'unesco_tentative',
        unescoRef: '1467',
        inscribedYear: 2000,
        lat: 32.4414,
        lng: 43.6022,
        civilization: 'العصر العباسي الإسلامي (القرن 8 الميلادي - ~775 م)',
        period: 'العصر العباسي الأول',
        descriptionAr: 'تحفة معمارية عسكرية إسلامية فريدة وسط البادية الغربية جنوب غرب كربلاء. قصر محصن بسور دفاعي ضخم مدعم بـ 48 برجاً نصف دائري. يجسد تطور القباب والعقود والسراديب في العمارة العباسية المبكرة، ويضم مسجداً ومقصورة ملكية وصحوناً متعددة.',
        descriptionEn: 'A magnificent fortified desert palace of the early Abbasid period (c. 775 CE). Features a massive stone curtain wall with 48 semi-circular bastions, arches, and early ribbed vaults.',
        keyMonuments: ['السور المحصن والأبراج الـ 48', 'الصحن الملكي والبهو المقبب', 'المسجد الأثري والسراديب'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/1467/'
      },
      {
        id: 'tentative-wasit',
        nameAr: 'مدينة واسط التاريخية',
        nameEn: 'Wasit Islamic City',
        ancientName: 'واسط القصب',
        governorate: 'واسط',
        category: 'unesco_tentative',
        unescoRef: '1468',
        inscribedYear: 2000,
        lat: 32.2358,
        lng: 46.2917,
        civilization: 'العصر الأموي والعباسي (تأسست 83 هـ / 702 م)',
        period: 'العصر الأموي والعباسي',
        descriptionAr: 'أسسها الحجاج بن يوسف الثقفي كحاضرة عسكرية استراتيجية تتوسط المسافة بين الكوفة والبصرة والأهواز. تضم بقايا المسجد الجامع الكبير بمحاريبه الثلاثة التاريخية الفريدة، وقصر القبة الخضراء، والمئذنة الأثرية، وأطلال دار الإمارة والأسواق القديمة.',
        descriptionEn: 'Early Islamic city founded by Al-Hajjaj in 702 CE midway between Kufa and Basra. Home to the monumental Friday Mosque with unique layered mihrabs and the Green Dome Palace.',
        keyMonuments: ['مسجد واسط الجامع بمحاريبه الثلاثة', 'قصر القبة الخضراء', 'منارة واسط الأثرية'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/1468/'
      },
      {
        id: 'tentative-bestansur',
        nameAr: 'مستوطنة بستان سور النيوليتية',
        nameEn: 'Bestansur Neolithic Settlement',
        ancientName: 'بستان سور',
        governorate: 'السليمانية',
        category: 'unesco_tentative',
        unescoRef: '6172',
        inscribedYear: 2017,
        lat: 35.3789,
        lng: 45.6475,
        civilization: 'العصر الحجري الحديث ما قبل الفخار (7700 - 7100 ق.م)',
        period: 'فجر الزراعة والاستقرار البشري',
        descriptionAr: 'تقع في سهل شهرزور الخصيب وتعد من أقدم القرى الزراعية المكتشفة في منطقة الهلال الخصيب. كشفت تنقيبات جامعة ريدينغ البريطانية عن أقدم مبانٍ طينية مستطيلة، ومدافن جماعية تضم أكثر من 70 فرداً تحت أرضيات البيوت مع قلائد من الخرز وحجر الأوبسيديان والأصداف البحرية المستوردة من مسافات شاسعة.',
        descriptionEn: 'Early Neolithic farming community in the Shahrizor Plain (c. 7700-7100 BCE). Excavations uncovered mudbrick dwellings and multi-individual burials with imported obsidian and sea shells.',
        keyMonuments: ['المبنى التذكاري ذو الأعمدة الطينية', 'المدافن الطقسية تحت الأرضيات', 'أقدم دلائل التجارة الإقليمية للأوبسيديان'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/6172/'
      },
      {
        id: 'tentative-mosul',
        nameAr: 'مدينة الموصل القديمة والجامع النوري',
        nameEn: 'Old City of Mosul',
        ancientName: 'الحدباء (الموصل القديمة)',
        governorate: 'نينوى',
        category: 'unesco_tentative',
        unescoRef: '6355',
        inscribedYear: 2018,
        lat: 36.3436,
        lng: 43.1275,
        civilization: 'العمارة الإسلامية والأتابكية والزنكية والتراثية',
        period: 'من القرن 12 الميلادي حتى العصر الحديث',
        descriptionAr: 'مركز حضري عريق على الضفة الغربية لنهر دجلة، مشهور بعمارة الحجر الجيري والرخام الموصلي (الفرش). تحتضن جامع النوري الكبير ومئذنته المائلة التاريخية "الحدباء" (القرن 12 م - عهد نور الدين زنكي)، وكنيسة الطاهرة للسريان الكاثوليك، وكنيسة الساعة، والأسواق والحمامات التراثية.',
        descriptionEn: 'Historic core on the western bank of Tigris. Features the 12th-century Al-Nuri Mosque and its leaning Al-Hadba minaret, Al-Tahera Syriac Catholic Church, and rich marble townhouses.',
        keyMonuments: ['جامع النوري ومئذنة الحدباء', 'كنيسة الطاهرة للسريان', 'كنيسة الساعة للآباء الدومنيكان', 'البيوت التراثية الرخامية'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/6355/'
      },
      {
        id: 'tentative-kirkuk-citadel',
        nameAr: 'قلعة كركوك التاريخية',
        nameEn: 'Kirkuk Citadel',
        ancientName: 'Arrapkha (أرابخا الآشورية)',
        governorate: 'كركوك',
        category: 'unesco_tentative',
        unescoRef: '6522',
        inscribedYear: 2021,
        lat: 35.4719,
        lng: 44.3942,
        civilization: 'الحضارة الآشورية، السلوقية، الإسلامية والعثمانية',
        period: 'أكثر من 3000 عام من التعاقب الحضاري',
        descriptionAr: 'ترتفع القلعة على تل أثري عتيق في قلب مدينة كركوك، شيدت فوق مدينة "أرابخا" الآشورية القديمة. تضم معالم تاريخية تعكس التنوع العراقي العريق: جامع النبي دانيال، وكنيسة أم الأحزان الكلدانية، والقبة الخضراء الأيوبية، وبيوت القلعة التراثية المشيدة بالآجر والجص الموصلي.',
        descriptionEn: 'Historic citadel standing on the ancient tell of Assyrian Arrapkha. Contains the Prophet Daniel shrine, the Green Dome, the Chaldean Church, and ornate Ottoman-era brick residences.',
        keyMonuments: ['مرقد وقبة النبي دانيال', 'القبة الخضراء السلجوقية', 'كنيسة أم الأحزان الأثرية', 'الأسوار والبيوت التراثية'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/6522/'
      },
      {
        id: 'tentative-amadiya',
        nameAr: 'مدينة العمادية التاريخية الحصينة',
        nameEn: 'Amedy City & Fortress',
        ancientName: 'Amadiya / Amedi',
        governorate: 'دهوك',
        category: 'unesco_tentative',
        unescoRef: '5601',
        inscribedYear: 2011,
        lat: 37.0911,
        lng: 43.4878,
        civilization: 'الأورارتية، الميدية، الآشورية، والإمارة البهدينانية التاريخية',
        period: 'الألف الأول ق.م حتى القرن 19 م',
        descriptionAr: 'مدينة أثرية معلقة على قمة هضبة جبلية بيضاوية مقطوعة الحواف ترتفع 1400 متر عن سطح البحر. عاصمة إمارة بهدينان التاريخية. تضم بوابة بهدينان الحجرية المنحوتة بأشكال النسور والفرسان، ومئذنة جامع العمادية الكبير (القرن 12 م) بارتفاع 30 متراً، ومدرسة قوبهان التاريخية وكنسية ومقابر أثرية.',
        descriptionEn: 'Dramatic cliff-top fortified town built on a natural plateau 1,400m above sea level. Capital of the Bahdinan Emirate with ancient carved gates, a 30m minaret, and Qubahan Madrasa.',
        keyMonuments: ['بوابة بهدينان (بوابة زيبار)', 'مئذنة جامع العمادية الكبير', 'مدرسة قوبهان الفقهية', 'بوابة الموصل الحجرية'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/5601/'
      },
      {
        id: 'tentative-lalish',
        nameAr: 'معبد لالش النوراني',
        nameEn: 'Lalish Temple',
        ancientName: 'لالش النوراني',
        governorate: 'نينوى',
        category: 'unesco_tentative',
        unescoRef: '6467',
        inscribedYear: 2020,
        lat: 36.7714,
        lng: 43.3039,
        civilization: 'التراث الديني والتاريخي العريق في وادي لالش',
        period: 'يمتد لآلاف السنين في شمال العراق',
        descriptionAr: 'المعبد الأكثر قدسية لأبناء الديانة الإيزيدية في العالم، يقع في وادٍ جبلي هادئ تحيط به أشجار البلوط والينابيع العذبة. يتميز بقبابه المخروطية المضلعة ذات الـ 24 ضلعاً التي ترمز لسطوع أشعة الشمس، وبوابة المعمدانية المنحوتة برمز الثعبان الأسود، وعين البيضاء المقدسة.',
        descriptionEn: 'The holiest temple of the Yazidi community worldwide. Nestled in a sacred mountain valley, featuring conical fluted spires representing sunbeams, holy springs, and the shrine of Sheikh Adi.',
        keyMonuments: ['القباب المخروطية الشمسية', 'مزار الشيخ عدي بن مسافر', 'العين البيضاء المقدسة (كانييا سبي)', 'بوابة المعبد المنحوتة'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/6467/'
      },
      {
        id: 'tentative-darb-zubaydah',
        nameAr: 'طريق الحج الكوفي: درب زبيدة في العراق',
        nameEn: 'Darb Zubaydah Pilgrimage Route in Iraq',
        ancientName: 'طريق الحج الكوفي',
        governorate: 'النجف',
        category: 'unesco_tentative',
        unescoRef: '6576',
        inscribedYear: 2022,
        lat: 31.4250,
        lng: 44.2100,
        civilization: 'الخلافة العباسية الإسلامية (القرن 8 - 10 الميلادي)',
        period: 'العصر العباسي الذهبي',
        descriptionAr: 'طريق القوافل والحج التاريخي الرابط بين الكوفة ومكة المكرمة، أنشئ وطور برعاية الخليفة العباسي هارون الرشيد وزوجته السيدة زبيدة. يضم منظومة هندسية مائية فريدة تتألف من برك مائية مدرجة، وآبار قاعية، واستراحات محصنة ومنارات إرشادية وسط البادية.',
        descriptionEn: 'Historic trans-desert pilgrimage route linking Kufa to Mecca, endowed by Abbasid Queen Zubaydah. Features monumental stepped water reservoirs (birak), wells, fortified caravanserais, and beacons.',
        keyMonuments: ['بركة القادسية والمسجد', 'محطة العذيب واستراحة القوافل', 'برك الشراف والمنارات الإرشادية'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/6576/'
      },
      {
        id: 'tentative-wadi-alsalam',
        nameAr: 'مقبرة وادي السلام التاريخية في النجف الأشرف',
        nameEn: 'Wadi Al-Salam Cemetery in Najaf',
        ancientName: 'وادي السلام / الغري',
        governorate: 'النجف',
        category: 'unesco_tentative',
        unescoRef: '5578',
        inscribedYear: 2011,
        lat: 32.0069,
        lng: 44.3161,
        civilization: 'التراث الإسلامي والإنساني (أكثر من 1400 عام متواصلة)',
        period: 'من صدر الإسلام حتى اليوم',
        descriptionAr: 'أضخم وأقدم مقبرة مستمرة في العالم الإسلامي تمتد على مساحة تزيد عن 600 هكتار، وتضم مدافن ملايين البشر عبر 14 قرناً، بجوار مرقد الإمام علي بن أبي طالب (ع). تتميز بعمارتها الجنائزية الفريدة، والسراديب والقبور الحجرية المحفورة في صخرة النجف، ومقامات الأنبياء هود وصالح.',
        descriptionEn: 'The largest and oldest continuously active Islamic cemetery in the world spanning over 600 hectares. Houses tombs of historical figures, traditional underground crypts, and prophet shrines.',
        keyMonuments: ['مقامات الأنبياء هود وصالح', 'السرداب التاريخي والسراديب العائلية', 'القباب الجنائزية الجصية التراثية'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/5578/'
      },
      {
        id: 'tentative-thilkifl',
        nameAr: 'موقع ذي الكفل الأثري والتراثي',
        nameEn: 'The Historic Site of Thilkifl',
        ancientName: 'شوشة / مرقد حزقيال',
        governorate: 'بابل',
        category: 'unesco_tentative',
        unescoRef: '5497',
        inscribedYear: 2010,
        lat: 32.2272,
        lng: 44.3756,
        civilization: 'العصر البابلي، الإيلخاني، والإسلامي العثماني',
        period: 'من القرن 6 ق.م حتى القرن 19 م',
        descriptionAr: 'موقع ديني وتاريخي مشترك على ضفاف شط الحلة يضم مرقد النبي حزقيال (ذو الكفل). تشتهر بمئذنتها التاريخية المضلعة الفريدة التي شيدها السلطان الإيلخاني محمد أولجايتو (خدابنده) في القرن 14 م والمزينة بمقرنصات جصية هندسية بديعة، وسوق الخانات التراثي الملحق.',
        descriptionEn: 'Ancient pilgrimage sanctuary on the Euphrates branch containing the shrine of Prophet Ezekiel (Dhul-Kifl). Renowned for its 14th-century Ilkhanid minaret adorned with intricate stalactite stucco.',
        keyMonuments: ['المئذنة الإيلخانية المقرنصة', 'مرقد النبي حزقيال (ذو الكفل)', 'الخانات والقيصرية التراثية'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/5497/'
      },
      {
        id: 'tentative-baghdad-rusafa',
        nameAr: 'معالم دجلة التاريخية في رصافة بغداد (المستنصرية والقصر العباسي)',
        nameEn: 'Historical Features of the Tigris in Baghdad Rusafa',
        ancientName: 'بغداد دار السلام',
        governorate: 'بغداد',
        category: 'unesco_tentative',
        unescoRef: '5880',
        inscribedYear: 2014,
        lat: 33.3386,
        lng: 44.3889,
        civilization: 'الخلافة العباسية الإسلامية والتراث البغدادي (القرن 12 - 13 م)',
        period: 'العصر العباسي المتأخر',
        descriptionAr: 'الشريط التراثي الأبرز على ضفاف نهر دجلة في رصافة بغداد. يضم المدرسة المستنصرية العريقة التي أسسها الخليفة المستنصر بالله عام 1233 م كأول جامعة أهلية تدرس المذاهب الأربعة والطب والفلك بساعتها المائية العجيبة، والقصر العباسي المطل على دجلة بمقرنصاته الآجرية الخالدة، وجامع الآصفية وسوق الصفافير.',
        descriptionEn: 'The historic urban riverfront along the Tigris in Rusafa. Encompasses Mustansiriya Madrasa (1233 CE) - the world\'s oldest four-rite university, the Abbasid Palace, and historic souks.',
        keyMonuments: ['المدرسة المستنصرية وساعتها التاريخية', 'القصر العباسي ومقرنصاته الآجرية', 'جامع السراي ومبنى القشلة', 'منارة سوق الغزل (جامع الخلفاء)'],
        unescoUrl: 'https://whc.unesco.org/en/tentativelists/5880/'
      },

      // =========================================================================
      // 3. المعالم الأثرية الوطنية المسجلة لدى الهيئة العامة للآثار (SBAH National)
      // =========================================================================
      {
        id: 'sbah-girsu',
        nameAr: 'كيرسو / تلو (حاضرة الأمير كوديا وأقدم جسر في العالم)',
        nameEn: 'Ancient Girsu (Tell Telloh)',
        ancientName: 'Ĝirsu (كيرسو)',
        governorate: 'ذي قار',
        category: 'national_registered',
        unescoRef: 'SBAH-GI-01',
        inscribedYear: 'مسجل رسمياً',
        lat: 31.5542,
        lng: 46.1558,
        civilization: 'الحضارة السومرية (عاصمة سلالة لجش الثانية ~2150 ق.م)',
        period: 'العصر السومري الذهبي',
        descriptionAr: 'العاصمة الدينية والإدارية لمملكة لجش السومرية ومقر الأمير المصلح كوديا. اكتشفت فيها تماثيل كوديا الشهيرة المصنوعة من حجر الديوريت الأسود المعروضة في اللوفر. تضم "جسر تلو" وهو أقدم جسر مقوس مشيد من الآجر الموقود في تاريخ البشرية (2200 ق.م)، ومعبد نينجيرسو إله الحرب السومري.',
        descriptionEn: 'Religious capital of Lagash II under Prince Gudea. Discoveries include famous diorite Gudea statues and the Bridge of Girsu - the oldest standing brick bridge in human history (c. 2200 BCE).',
        keyMonuments: ['جسر تلو المقوس (أقدم جسر في التاريخ)', 'معبد نينجيرسو (الإينينو)', 'قصر الأمير كوديا السومري'],
        unescoUrl: null
      },
      {
        id: 'sbah-lagash',
        nameAr: 'مدينة لجش الأثرية (تل الهباء)',
        nameEn: 'Ancient Lagash (Tell al-Hiba)',
        ancientName: 'Lagaš (لجش)',
        governorate: 'ذي قار',
        category: 'national_registered',
        unescoRef: 'SBAH-LA-02',
        inscribedYear: 'مسجل رسمياً',
        lat: 31.4111,
        lng: 46.4022,
        civilization: 'الحضارة السومرية (فجر السلالات ~2900 - 2350 ق.م)',
        period: 'عصر فجر السلالات السومري',
        descriptionAr: 'واحدة من أضخم المدن الأثرية في الشرق الأدنى القديم تمتد على مساحة 600 هكتار. حاضرة الملك أور-نانشة وإياناتوم صاحب "مسلة النسور". كشفت أحدث تنقيبات البعثة الأمريكية-العراقية (2023) عن أقدم مطعم وحانة عامة في التاريخ مع فرن طهي وأوعية طعام ونظام تبريد طيني.',
        descriptionEn: 'Massive Sumerian city spanning 600 hectares, home of King Eannatum (Stele of the Vultures). 2023 excavations revealed an intact 5,000-year-old public tavern with an oven and clay food vessels.',
        keyMonuments: ['معبد إيبغال البيضاوي المخصص لإنانا', 'المطعم والحانة السومرية المكتشفة 2023', 'ورش الخزف والمسلات النذرية'],
        unescoUrl: null
      },
      {
        id: 'sbah-borsippa',
        nameAr: 'بورسيبا وزقورة برس نمرود',
        nameEn: 'Borsippa (Birs Nimrud)',
        ancientName: 'Barsip (بورسيبا)',
        governorate: 'بابل',
        category: 'national_registered',
        unescoRef: 'SBAH-BO-03',
        inscribedYear: 'مسجل رسمياً',
        lat: 32.3917,
        lng: 44.3417,
        civilization: 'الحضارة البابلية (العهد البابلي الحديث ~600 ق.م)',
        period: 'العصر البابلي الحديث',
        descriptionAr: 'المدينة التوأم لبابل ومركز عبادة الإله نابو، إله الحكمة والكتابة وابن الإله مردوخ. زقورتها الهائلة "إيوريمينانكي" لا تزال تنتصب بارتفاع يقارب 47 متراً، وكان الرحالة الأوائل يظنونها برج بابل التوراتي. تضم معبد إيزيدا الملكي الذي رممه الملك نبوخذ نصر الثاني.',
        descriptionEn: 'The sister city of Babylon dedicated to Nabu, god of wisdom. Its towering ruined ziggurat (Euriminanki) still rises 47m. Features the Ezida temple complex restored by Nebuchadnezzar II.',
        keyMonuments: ['زقورة بورسيبا الشامخة', 'معبد إيزيدا للإله نابو', 'الكتل الآجرية المزججة الأصلية'],
        unescoUrl: null
      },
      {
        id: 'sbah-kish',
        nameAr: 'كيش / تل الأحيمر (مهد الملوكية بعد الطوفان)',
        nameEn: 'Ancient Kish (Tell al-Uhaymir)',
        ancientName: 'Kiš (كيش)',
        governorate: 'بابل',
        category: 'national_registered',
        unescoRef: 'SBAH-KI-04',
        inscribedYear: 'مسجل رسمياً',
        lat: 32.5414,
        lng: 44.6050,
        civilization: 'الحضارة السومرية والأكدية (~3100 - 500 ق.م)',
        period: 'عصر فجر السلالات السومري الأول',
        descriptionAr: 'المدينة التاريخية الخالدة التي ذكرت نصوص بلاد الرافدين أن الملوكية هبطت فيها أولاً بعد الطوفان الكبير. أخذ ملوك سومر لقب "ملك كيش" كدلالة على السيادة العالمية. تضم زقورة الأحيمر الحمراء المكرسة للإله زبابا، وقصر كيش السومري العتيق، وأقدم عربات مدولبة مكتشفة.',
        descriptionEn: 'Sumerian city where kingship descended after the Deluge. The title "King of Kish" denoted paramount rule. Features the red-brick ziggurat of Zababa and the monumental Early Dynastic Palace A.',
        keyMonuments: ['زقورة تل الأحيمر الحمراء', 'قصر كيش السومري (Palace A)', 'معبد الإله زبابا وعشتار'],
        unescoUrl: null
      },
      {
        id: 'sbah-ctesiphon',
        nameAr: 'طاق كسرى والمدائن (إيوان كسرى العظيم)',
        nameEn: 'Ctesiphon & Taq Kasra',
        ancientName: 'Tisfūn (طسفون / المدائن)',
        governorate: 'بغداد',
        category: 'national_registered',
        unescoRef: 'SBAH-CT-05',
        inscribedYear: 'مسجل رسمياً',
        lat: 33.0936,
        lng: 44.5811,
        civilization: 'الإمبراطورية الفرثية والساسانية (القرن 3 - 6 م)',
        period: 'العصر الساساني والفرثي',
        descriptionAr: 'عاصمة الإمبراطورية الساسانية الكبرى على ضفاف دجلة جنوب بغداد. تحتضن "طاق كسرى"، وهو أضخم قوس مبني من الآجر غير المسلح في العالم بقوس إيواني مفرد يرتفع 37 متراً وبعرض 25.5 متراً، معجزة معمارية صمدت عبر 15 قرناً.',
        descriptionEn: 'The grand Sasanian imperial capital on the Tigris. Home to Taq Kasra, the world\'s largest single-span unreinforced brick vault (37m high, 25.5m wide), an engineering wonder of antiquity.',
        keyMonuments: ['إيوان كسرى المقوس العظيم', 'واجهة القصر الساساني الشامخة', 'مرقد الصحابي سلمان المحمدي'],
        unescoUrl: null
      },
      {
        id: 'sbah-tell-harmal',
        nameAr: 'تل حرمل / شادوبوم (مركز الرياضيات والعلوم البابلية)',
        nameEn: 'Tell Harmal (Ancient Shaduppum)',
        ancientName: 'Šaduppûm (بيت الحساب والضرائب)',
        governorate: 'بغداد',
        category: 'national_registered',
        unescoRef: 'SBAH-TH-06',
        inscribedYear: 'مسجل رسمياً',
        lat: 33.3117,
        lng: 44.4772,
        civilization: 'العصر البابلي القديم ومملكة إشنونا (القرن 19 - 18 ق.م)',
        period: 'العصر البابلي القديم',
        descriptionAr: 'مدينة أثرية متكاملة تقع في قلب بغداد الجديدة، نقبها العلامة العراقي طه باقر. أحدثت اكتشافاتها ثورة علمية في تاريخ الرياضيات، حيث عثر فيها على ألواح طينية تبرهن تشابه المثلثات القائمة وتسبق مبرهنة فيثاغورس الإغريقية بأكثر من ألف عام، بالإضافة إلى شريعة إشنونا الشهيرة.',
        descriptionEn: 'Ancient administrative and educational center inside modern Baghdad. Unearthed mathematical tablets proving geometric principles that predate Pythagoras by over a millennium.',
        keyMonuments: ['معبد الإلهة نيسابا (إلهة الكتابة والرياضيات)', 'ألواح الهندسة الرياضية المسمارية', 'مبنى الإدارة ومكاتب الخزينة'],
        unescoUrl: null
      },
      {
        id: 'sbah-khorsabad',
        nameAr: 'دور شروكين / خورسباد (عاصمة سرجون الثاني)',
        nameEn: 'Khorsabad (Dur-Sharrukin)',
        ancientName: 'Dūr-Šarrukīn (حصن سرجون)',
        governorate: 'نينوى',
        category: 'national_registered',
        unescoRef: 'SBAH-KH-07',
        inscribedYear: 'مسجل رسمياً',
        lat: 36.5097,
        lng: 43.2289,
        civilization: 'الإمبراطورية الآشورية الحديثة (عهد سرجون الثاني 721 - 705 ق.م)',
        period: 'العصر الآشوري الحديث',
        descriptionAr: 'المدينة الملكية النموذجية التي بناها الملك الآشوري سرجون الثاني من الصفر كعاصمة جديدة لإمبراطوريته شمال الموصل. تتميز بقصرها الملكي المشيد فوق مصطبة مرتفعة، وثيرانها المجنحة الهائلة المنحوتة بأرجل خمسة، وجدرانها المكسوة بألواح النحت البارز التي تصور الفتوحات الآشورية.',
        descriptionEn: 'The purpose-built imperial capital of Sargon II, inaugurated in 706 BCE. Renowned for its elevated royal palace, colossal winged bulls (lamassu), and monumental stone reliefs.',
        keyMonuments: ['قصر سرجون الثاني الملكي', 'زقورة خورسباد الحلزونية الملونة', 'بوابات الثيران المجنحة'],
        unescoUrl: null
      },
      {
        id: 'sbah-jarmo',
        nameAr: 'موقع جرمو الأثري (أقدم قرية زراعية في العالم 7000 ق.م)',
        nameEn: 'Jarmo Prehistoric Settlement',
        ancientName: 'Qal\'at Jarmo',
        governorate: 'كركوك',
        category: 'national_registered',
        unescoRef: 'SBAH-JA-08',
        inscribedYear: 'مسجل رسمياً',
        lat: 35.5567,
        lng: 44.9547,
        civilization: 'العصر الحجري الحديث الزراعي (7090 - 5000 ق.م)',
        period: 'فجر الثورة النيوليتية الزراعية',
        descriptionAr: 'يقع في سفوح جبال زاغروس قرب جمجمال، ويعد من أهم المواقع الأثرية في العالم لدراسة نشوء الزراعة واستئناس الحيوان. كشفت أبحاث روبرت بريدوود عن قرية تضم نحو 25 بيتاً طينياً مستقراً، وأقدم حبات قمح وشعير مدجنة، وحيوانات مستأنسة، وأوانٍ حجرية مصقولة بدقة فائقة.',
        descriptionEn: 'Pioneering agricultural site excavated by Robert Braidwood. One of the earliest fully established farming villages (c. 7090 BCE), evidence of domesticated emmer, barley, sheep, and goats.',
        keyMonuments: ['أقدم البيوت الطينية الزراعية', 'مطاحن الحبوب الحجرية الأولى', 'تماثيل الخصوبة الطينية'],
        unescoUrl: null
      },
      {
        id: 'sbah-shanidar',
        nameAr: 'كهف شانيدر الأثري (أقدم رفات إنسان نياندرتال وطقوس الزهور)',
        nameEn: 'Shanidar Cave',
        ancientName: 'أشكفتي شانيدر',
        governorate: 'أربيل',
        category: 'national_registered',
        unescoRef: 'SBAH-SH-09',
        inscribedYear: 'مسجل رسمياً',
        lat: 36.8344,
        lng: 44.2181,
        civilization: 'العصر الحجري القديم الأوسط والأعلى (65,000 - 35,000 عام مضت)',
        period: 'عصر إنسان النياندرتال والباليوليت',
        descriptionAr: 'يقع في جبل برادوست شمال شرق أربيل ويطل على وادي الزاب الكبير. كشف عن بقايا هياكل عظمية لإنسان النياندرتال، أشهرها "دفن الزهور" (Shanidar IV) الذي أثبت وجود مشاعر تعاطف وطقوس جنائزية إنسانية عبر تغطية الموتى بزهور برية، واكتشاف "شانيدر Z" حديثاً (2020) بجامعة كامبريدج.',
        descriptionEn: 'World-famous Neanderthal site in the Bradost Mountains. Excavations yielded Neanderthal skeletons including the famous "Flower Burial" (Shanidar IV), showing compassion and burial rituals.',
        keyMonuments: ['موقع مدافن النياندرتال العظمية', 'طبقة حبوب لقاح الزهور الجنائزية', 'أدوات الصوان الموستيرية'],
        unescoUrl: null
      },
      {
        id: 'sbah-tell-es-sawwan',
        nameAr: 'تل الصوان الأثري (حضارة سامراء الحجرية 6000 ق.م)',
        nameEn: 'Tell es-Sawwan',
        ancientName: 'تل الصوان',
        governorate: 'صلاح الدين',
        category: 'national_registered',
        unescoRef: 'SBAH-TS-10',
        inscribedYear: 'مسجل رسمياً',
        lat: 34.1953,
        lng: 43.8967,
        civilization: 'حضارة سامراء النيوليتية (6000 - 5500 ق.م)',
        period: 'العصر الحجري الحديث المتأخر',
        descriptionAr: 'يقع على الضفة الشرقية لنهر دجلة جنوب سامراء. يمثل أقدم قرية محصنة بخندق دفاعي وسور من اللبن لحماية المجتمع الزراعي. اشتهر بتماثيله الرخامية الدقيقة المصقولة ذات العيون المرصعة بالقار والصدف، ومدافن الأطفال تحت أرضيات البيوت التي احتوت على تحف نفيسة من المرمر.',
        descriptionEn: 'Late Neolithic site south of Samarra, featuring the earliest known defensive ditch and mudbrick wall. World-famous for carved alabaster figurines with inlaid shell and bitumen eyes.',
        keyMonuments: ['أقدم خندق وسور دفاعي في العالم', 'تماثيل المرمر والألباستر السامسامرية', 'مخازن الحبوب والبيوت المنتظمة'],
        unescoUrl: null
      },
      {
        id: 'sbah-isin',
        nameAr: 'مدينة إيسن الأثرية (سلالة إيسن وشريعة لبت عشتار)',
        nameEn: 'Ancient Isin (Ishan al-Bahriyat)',
        ancientName: 'Isin (إيسن)',
        governorate: 'القادسية',
        category: 'national_registered',
        unescoRef: 'SBAH-IS-11',
        inscribedYear: 'مسجل رسمياً',
        lat: 31.8833,
        lng: 45.2667,
        civilization: 'سلالة إيسن السومرية والبابلية (2017 - 1794 ق.م)',
        period: 'عصر إيسن ولارسا',
        descriptionAr: 'عاصمة السلالة التي ورثت إمبراطورية أور الثالثة. أصدر ملكها لبت عشتار شريعته القانونية الشهيرة المكتوبة باللغة السومرية والتي سبقت شريعة حمورابي بنحو 150 عاماً. كانت المركز الرئيسي لعبادة الإلهة "غولا"، إلهة الشفاء والطب في بلاد الرافدين، ويضم معبدها قبوراً ومجسمات رمزية للكلاب المكرسة للشفاء.',
        descriptionEn: 'Major Mesopotamian city that succeeded Ur III. Site of the Code of Lipit-Ishtar (c. 1930 BCE) predating Hammurabi. Center of Gula, the goddess of medicine and healing.',
        keyMonuments: ['معبد الإلهة غولا (إيغالماخ)', 'قصر الملك إشمي داغان', 'مكتبة الألواح الطبية والمسمارية'],
        unescoUrl: null
      },
      {
        id: 'sbah-larsa',
        nameAr: 'مدينة لارسا الأثرية (تل سنكرة)',
        nameEn: 'Ancient Larsa (Tell as-Senkereh)',
        ancientName: 'Larsa (لارسا)',
        governorate: 'ذي قار',
        category: 'national_registered',
        unescoRef: 'SBAH-LA-12',
        inscribedYear: 'مسجل رسمياً',
        lat: 31.2858,
        lng: 45.8544,
        civilization: 'سلالة لارسا السومرية - الأمورية (2025 - 1763 ق.م)',
        period: 'عصر إيسن ولارسا والعهد البابلي القديم',
        descriptionAr: 'مملكة الجنوب الكبرى وغريمة بابل في عهد ملكها العظيم ريم سين الأول قبل أن يضمها حمورابي. كانت مركز عبادة إله الشمس "شمش" في جنوب الرافدين. تضم معبد إيبابار (البيت الساطع)، وقصر نور أداد الضخم، وعثر فيها على لوح "بليمبتون 322" الشهير الذي يحتوي على جداول مثلثات بابلية متطورة.',
        descriptionEn: 'Powerful kingdom ruled by King Rim-Sin I until conquered by Hammurabi. Center of solar deity Shamash, home to the Ebabbar temple and the mathematical tablet Plimpton 322.',
        keyMonuments: ['معبد إيبابار لإله الشمس شمش', 'قصر الملك نور أداد العظيم', 'الشبكة المائية وقنوات الري السومرية'],
        unescoUrl: null
      },
      {
        id: 'sbah-shuruppak',
        nameAr: 'مدينة شروباك الأثرية (تل فارة - موطن بطل الطوفان)',
        nameEn: 'Ancient Shuruppak (Tell Fara)',
        ancientName: 'Šuruppag (شروباك)',
        governorate: 'القادسية',
        category: 'national_registered',
        unescoRef: 'SBAH-SH-13',
        inscribedYear: 'مسجل رسمياً',
        lat: 31.7750,
        lng: 45.5139,
        civilization: 'الحضارة السومرية (فجر السلالات ~2900 - 2000 ق.م)',
        period: 'عصر فجر السلالات الأول والثاني',
        descriptionAr: 'وفق الأساطير السومرية وملحمة كلكامش، هي المدينة الأخيرة قبل الطوفان وموطن الملك الحكيم "زويسودرا" (أوتنابشتيم) الذي بنى سفينة النجاة بأمر الإله إنكي. أثبتت حفريات إريك شميدت وجود طبقة سميكة من الطمي الرسوبي تفصل بين الطبقات السكنية وتؤرخ لفيضان الرافدين الكارثي.',
        descriptionEn: 'The legendary hometown of Utnapishtim (Ziusudra), hero of the Sumerian Deluge myth. Archaeological excavations identified a thick flood silt layer matching the historic catastrophic inundation.',
        keyMonuments: ['طبقة غرين الطوفان الرسوبية التاريخية', 'ألواح تعليمات شروباك الأخلاقية السومرية', 'البيوت السومرية المستديرة'],
        unescoUrl: null
      },
      {
        id: 'sbah-drehem',
        nameAr: 'تل الدريهم / بوزريش دغان (خزينة إمبراطورية أور الثالثة)',
        nameEn: 'Puzrish-Dagan (Drehem)',
        ancientName: 'Puzriš-Dagan (حصن دغان)',
        governorate: 'القادسية',
        category: 'national_registered',
        unescoRef: 'SBAH-DR-14',
        inscribedYear: 'مسجل رسمياً',
        lat: 32.1000,
        lng: 45.0833,
        civilization: 'سلالة أور الثالثة السومرية (عهد الملك شولجي ~2050 ق.م)',
        period: 'العصر السومري الإمبراطوري',
        descriptionAr: 'المركز اللوجستي والمالي الأضخم لإمبراطورية أور الثالثة أنشأه الملك شولجي لتنظيم واردات الدولة من الماشية والقرابين والضرائب وتوزيعها على معابد نيبور وأور وأوروك. خرجت منه عشرات الآلاف من الألواح الإدارية الدقيقة التي وثقت أدق تفاصيل الاقتصاد والبيروقراطية السومرية.',
        descriptionEn: 'The massive administrative and livestock distribution hub of the Ur III Empire founded by King Shulgi. Source of tens of thousands of cuneiform economic and tax accounting tablets.',
        keyMonuments: ['مكاتب الخزينة وسجلات الضرائب المركزية', 'أحواض الماشية الملكية', 'مجمع الأرشيف المسماري'],
        unescoUrl: null
      },
      {
        id: 'sbah-tell-hassuna',
        nameAr: 'تل حسونة الأثري (حضارة حسونة 6000 ق.م)',
        nameEn: 'Tell Hassuna Prehistoric Site',
        ancientName: 'حسونة',
        governorate: 'نينوى',
        category: 'national_registered',
        unescoRef: 'SBAH-HA-15',
        inscribedYear: 'مسجل رسمياً',
        lat: 36.1667,
        lng: 43.1000,
        civilization: 'حضارة حسونة النيوليتية (6000 - 5500 ق.م)',
        period: 'العصر الحجري الفخاري القديم',
        descriptionAr: 'يقع جنوب الموصل، وهو الموقع النموذجي لـ "ثقافة حسونة" في شمال بلاد الرافدين. كشف عن فخار متطور ذي زخارف خطية محفورة، وأفران متقدمة لحرق الطين، ومساكن مستطيلة مقسمة لعدة غرف تخزين مع صوامع حفظ الحبوب، ما يشير لمجتمع زراعي مبكر منظم.',
        descriptionEn: 'Type site for the Hassuna culture of northern Mesopotamia (c. 6000 BCE). Famous for its incised and painted pottery, complex domed kilns, and multi-room farmhouse structures.',
        keyMonuments: ['أفران الخزف المتقدمة', 'أقدم صوامع تخزين الغلال', 'الفخار الحسوني المزخرف'],
        unescoUrl: null
      },
      {
        id: 'sbah-shirwana',
        nameAr: 'قلعة شروانه التاريخية',
        nameEn: 'Shirwana Castle',
        ancientName: 'قەڵای شێروانە',
        governorate: 'السليمانية',
        category: 'national_registered',
        unescoRef: 'SBAH-SW-16',
        inscribedYear: 'مسجل رسمياً',
        lat: 34.6225,
        lng: 45.3111,
        civilization: 'العمارة الدفاعية والقلاع في إقليم كردستان والعراق (القرن 19 م)',
        period: 'العصر المتأخر والتراثي',
        descriptionAr: 'قلعة مهيبة تشرف على نهر سيروان في قضاء كلار جنوب السليمانية. شيدها محمد باشا الجاف بين عامي 1866 و 1874 م فوق تل أثري ساساني عتيق. تتميز بطرازها الآجري الرصين، وبرجها المركزي ذي الشرفات الدفاعية الثمانية ومتحف الفلكلور والتراث الكردستاني.',
        descriptionEn: 'Striking brick fortress built on an ancient Sasanian tell in Kalar. Constructed by Mohamed Pasha Jaff (1866-1874 CE) featuring an octagonal central tower and defense balconies.',
        keyMonuments: ['البرج المثمن والمقصورة العسكرية', 'المدخل الآجري المعقود', 'متحف التراث والآثار'],
        unescoUrl: null
      },
      {
        id: 'sbah-khan-nukhailah',
        nameAr: 'خان النخيلة التراثي (خان الربع)',
        nameEn: 'Khan Al-Nukhailah (Khan Al-Rub\')',
        ancientName: 'خان النخيلة',
        governorate: 'كربلاء',
        category: 'national_registered',
        unescoRef: 'SBAH-KN-17',
        inscribedYear: 'مسجل رسمياً',
        lat: 32.5317,
        lng: 44.2056,
        civilization: 'العصر الإسلامي العثماني (القرن 18 الميلادي)',
        period: 'العصر العثماني الإسلامي',
        descriptionAr: 'يقع في ربع المسافة بين كربلاء والنجف وكان المحطة الرئيسية لحماية وإيواء قوافل الحجاج والتجار والمسافرين. يتميز بسوره الحصين من الآجر، ومدخله الضخم المعقود، وصحنه الداخلي الواسع المحاط بأروقة مسقوفة وإيوانات استراحة وإسطبلات محصنة ومسجد مدمج.',
        descriptionEn: 'Prominent 18th-century fortified caravanserai situated midway between Karbala and Najaf on the pilgrimage route. Features high brick walls, arched arcades, stables, and a mosque.',
        keyMonuments: ['البوابة الدفاعية ذات العقد المدبب', 'الأروقة والإيوانات المقببة', 'أبراج الزوايا الحصينة'],
        unescoUrl: null
      }
    ]
  };

  /**
   * Convert sites to standard GeoJSON FeatureCollection
   */
  IRAQ_ARCHAEOLOGY_DATA.toGeoJSON = function () {
    return {
      type: 'FeatureCollection',
      features: IRAQ_ARCHAEOLOGY_DATA.sites.map(site => ({
        type: 'Feature',
        id: site.id,
        geometry: {
          type: 'Point',
          coordinates: [site.lng, site.lat]
        },
        properties: { ...site }
      }))
    };
  };

  // Expose globally
  window.IRAQ_ARCHAEOLOGY_DATA = IRAQ_ARCHAEOLOGY_DATA;

})(window);
